[package]
name = "la-patate-chaude"
version = "0.1.0"
edition = "2021"

[lib]
name = "hashcash"
path = "src/hashcash/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"